spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:admin}
